### PR TITLE
heFFTe

### PR DESCRIPTION
**Pull request by stomov**
heFFTe compatibility form

### CODE REVIEW

**Comment by balos1** [comment]
heFFTe is compatible with the xSDK, so I recommend that we merge this PR even if heFFTe is not admitted an xSDK member package, and is only designated a xSDK compatible package (see the language from xsdk community policies below).

> We consider two categories of xSDK packages: xSDK compatible packages and xSDK member packages. We also consider two levels of xSDK compatibility: mandatory policies and recommended policies.
>
> * A package will be declared xSDK compatible once the xSDK team has determined that the package satisfies the mandatory xSDK policies listed below. In addition to the required policies, we specify recommended xSDK policies that further help to address issues in software interoperability.
> 
> * Similarly, a package can become an xSDK member package if (1) it is an xSDK-compatible package, and (2) it uses or can be used by another package in xSDK, and the connecting interface is regularly tested for regressions.

**Comment by balay** [comment]
I've added heffte to xsdk-0.6.0 branch - and it builds fine on the current 3 test cases..

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/192191316

https://github.com/xsdk-project/spack-xsdk/commit/37c51f11e531d52ba55bad574eb433608621c481

cc: @ulrikeyang

**Comment by stomov** [comment]
@balay That's great! Thanks. Meanwhile, we added a MAGMA dependency for heFFTe. We will follow up on this requirement when we make a next heFFTe release (v1.1 by the end of the month).

**Comment by balay** [comment]
Is there a develop or equivalent branch where the v1.1 related code is worked on?  - If so (If its not too broken) - its  would be good to start using it in spack/xsdk

**Comment by stomov** [comment]
We have different branches for different features until we merge them in master but not one for the upcoming v1.1. I will check with the other developers if we can make one to use it also for the xsdk testing, and will follow up tomorrow.

**Comment by balay** [comment]
Ah ok - so the features get merged to master - and the release is tagged on master.

So I can use master branch for now [Shouldn't need a special branch for xsdk.]

https://github.com/xsdk-project/spack-xsdk/commit/81c6231489733f15d2621da48e13eadc72fc92f5

[this can be updated when the release is created]

The other issue would be: spack changes  (to heffe package) to enable and build magma variant.

**Comment by stomov** [comment]
Sounds good. 
We will update the heFFTe spack package. For now we have cmake updated.

**Comment by mkstoyanov** [comment]
Guys,

I made the pull request for spack to include the +magma variant for heffte:

https://github.com/spack/spack/pull/18849

Once that is merged, we can add heffte to the main xSDK branch with:

heffte@develop

when using +cuda for xSDK, we should use heffte@develop+cuda+magma

The @develop will be upgraded to @1.1 when we make the next release.

Then only other question is whether we want to add a default CPU backend for heffte. We can add +fftw which is open source, but some people may not like the GPL license.

Miro

________________________________

**Comment by mkstoyanov** [comment]
The updated pull-request has been merged into spack-develop.

We can begin testing with:
```
spack install heffte@develop+fftw+cuda+magma
```

**Comment by balos1** [comment]
Since heFFTe now has a dependency on magma, it qualifies to be a full xsdk member package.

**Review by balos1 — APPROVED** [review]

**Pull request merged**
