### PR TITLE
adding dtk policy compatibility

### PR DESCRIPTION
**Pull request by sslattery**

### CODE REVIEW

**Comment by aprokop** [comment]
@sslattery Should we mention initialization/finalization of Kokkos in M6?

**Comment by sslattery** [comment]
Thanks @aprokop - I have added something regarding Kokkos to M6

**Comment by aprokop** [comment]
This was merged too quickly, and @dalg24's proposed changes were not applied to the merge commit.

**Comment by balos1** [comment]
@aprokop Sorry about that, for some reason I thought they were applied already. Can you open a new PR to make the suggested changes?

**Pull request merged**
